import { Outfit } from 'next/font/google';
import './globals.css';
import { SidebarProvider } from '@/context/SidebarContext';
import { ThemeProvider } from '@/context/ThemeContext';
import { LoadingProvider } from '@/context/LoadingContext';
import GlobalLoader from '@/components/common/GlobalLoader';
import MainLayout from '@/layouts/MainLayout';
import { ToastProvider } from '@/context/ToastContext';
import { AuthProvider } from '@/context/AuthContext';

const outfit = Outfit({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, pageProps }) {
  return (
     <html lang="en">
      <body className={`${outfit.className} dark:bg-gray-900`}>
         <AuthProvider>
        <ThemeProvider>
           <ToastProvider>
        <MainLayout>
          <LoadingProvider>
            <GlobalLoader/>
          <SidebarProvider>{children}</SidebarProvider>
          </LoadingProvider>
        </MainLayout>
        </ToastProvider>
        </ThemeProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
